string[] positiveDialogues = new string[] {
        "This city rocks!",
"You are such a good crowd!",
"Your city is beautiful <3",
"First row: youre beautiful",
"You are good singers!",
"Hands up!",
"I love you!",
"Spread the love",
"I like you",
"I like your style",
"This crowd is really nice",
"You are amazing",
"We can do it !",
"Lets rock this house",
"We can achieve anything",
"Never give up",
"We can achieve it together!",
"Live what you love",
"All you need is love",
"This is a really good game",
"Lets together break the 4th Wall!",
"Choose this one !",
"I pay the next round",
"You really know the lyrics!",
"<3",
"Trust this game",
"The programmers knew what they did",
"Love your bling-bling",
"Boo Ya!",
"You rock the crib",
"Who's all crunk?",
"You're dope!",
"Who's down for another song ?",
"Who wants free dubs?",
"I want a baby from you!",
"You guys are fly af",
"This is some fresh shit, yo!",
"You guys freakin' rock!",
"Giddy Up!",
"How's it hangin'?",
"Guys, I jock your shit!",
"Nice!",
"Let's murk",
"OMG <3",
"Snaps !",
"Sup people",
"I like that you're Straight Edge",
"This city's pretty tight",
"Yo, yo, homie Joe",
"I see a lot of hotties in the crowd!",
"You go!",
"You're all that and a bag of chips",
"You're my home skillets",
"All the homies in the house say YEAAAAHHH !!",
"Aiight lets do this",
"Hella good mood here!",
"You go, dude!",
"You go, girl!",
"Who's up for some good fkin music?!",
"Unmute your computer, this song sounds awesome ",
"Open up a big circle here in the front",
"Here have some cold water in the first rows",
"We'll play some encore later",
"Sing along: a-one, two, a-one two three",
"Free shots for everyone ",
"Stage-Diving is our passion",
"Jump, Jump, Jump !!",
"Put your hands up in the air as if you dont care!!",
    };

    string[] negativeDialogues = new string[] {
        "Crowd surfing is not prohibited",
"Free shots for me only",
"Nobody likes encores anyway, right ?",
"Whatever, dude",
"Oh good she's a monet!!",
"I'm not stayin' with you fart-knockers",
"So many scrubs here tonight",
"Your Mom",
"Who's your daddy",
"I'm better than you",
"I made your momma my bitch",
"You're all wangstas",
"Talk to the hand (because the face ain't listening)",
"Step Off",
"So Is Your Face",
"You're such shooters",
"You' some shady mofos!",
"Who stole my LSD ?",
"You're getting punked on",
"I wanna see your punanies",
"I'm gonna open up a can of whoop-ass",
"You oogly",
"O...M...F...G...",
"You Mofos",
"...Erm... Er... Yeah....",
"I'm gonna jack you up",
"Where my Hochies at ?",
"You will all get ganked tonight",
"FYI -> i dont care about you",
"Eat my shorts!",
"Screw you!",
"You guys killed my buzz",
"Please bounce",
"I'm making so much bones of you guys",
"Beeotch",
"Biiiittchh",
"You guys are rednecks",
"Back in the days the crowd was good",
"I love you... as if!",
"Let's dip",
"Don't trust this game",
"#$@&☠%*!",
"Donate money to me!",
"#$@&☠%*! your moral bullshit",
"You are a cunt",
"Already loose!",
"Take the other one !",
"I hope you step on lego",
"I dont care about your opinion",
"I begin to hate you",
"Leave",
"I hate you !",
"I control you !",
"You sing bad!",
"Why do you not like it?",
"This city sucks!",
"You suck!",
"Can you sing along correctly ?",
"This is just a shitty game",
"Your ugliness dazzles me",
"Why are you so bad ?",
"Leave now!",
"Kill yourself",
"People are shit",
"Don't choose this one"
    };
